### ISSUE TITLE
テキスト教材の読破済み機能

### ISSUE THREAD

**Issue by iloveomelette** [yanbaru-expert/team_project_62#24]

**Comment by kuramoto30** [comment]
## 実装内容
「タスク#15」完了後に行う
 - 読破済み機能に使用する ReadProgress モデルを作成
   - 外部キー設定を行い，ユニーク制約を入れてからマイグレーション
   - バリデーションをモデルに追加
   - 関連付けを入れる（User と Text の関連付けは使用しないので入れなくてもOK）
 - テキスト教材一覧ページに読破済み機能を実装
   - 詳細ページには実装しない
   - 非同期で処理
